; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-wroom-32d]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = 
	-D CONFIG_FREERTOS_HZ=1000
	-D SQLITE_ENABLE_UPDATE_DELETE_LIMIT=1
	-Wno-error=discarded-qualifiers
board_build.filesystem = spiffs
lib_deps = 
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit BusIO@^1.16.2
	adafruit/Adafruit Unified Sensor@^1.1.14
	adafruit/DHT sensor library@^1.4.4
	ArduinoJson@^6.18.5
	https://github.com/siara-cc/esp32_arduino_sqlite3_lib
	ayushsharma82/ElegantOTA @ ^3.1.7
	adafruit/RTClib@^2.1.4
